# Generated by Django 3.0 on 2019-12-16 16:46

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField()),
                ('image', models.ImageField(height_field='_height', upload_to=backend.models.path_to_image, width_field='_width')),
            ],
        ),
    ]
