# Generated by Django 3.0 on 2019-12-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goat',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goat',
            name='n_battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goat',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goat',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
