# Generated by Django 3.0 on 2019-12-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_goat_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goat',
            name='score',
        ),
    ]
