# Generated by Django 3.0 on 2019-12-17 11:24

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_goat_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='score',
            field=models.FloatField(default=backend.models.get_initial_score),
        ),
    ]
