# Generated by Django 3.0 on 2019-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_goat_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
